### ISSUE TITLE
Error: Process exited with status 1

### ISSUE THREAD

**Issue by fzhedu** [pingcap-incubator/tiup-cluster#236]
+ Copy files
  - Copy pd -> 172.16.5.70 ... Error
  - Copy pd -> 172.16.5.71 ... Error
  - Copy pd -> 172.16.5.72 ... Error
  - Copy tikv -> 172.16.5.70 ... Error
  - Copy tikv -> 172.16.5.71 ... Error
  - Copy tikv -> 172.16.5.72 ... Error
  - Copy tidb -> 172.16.5.69 ... Error
  - Copy tiflash -> 172.16.5.70 ... Error
  - Copy tiflash -> 172.16.5.71 ... Error
  - Copy tiflash -> 172.16.5.72 ... Error
  - Copy prometheus -> 172.16.5.70 ... Error
  - Copy grafana -> 172.16.5.71 ... Error
  - Copy alertmanager -> 172.16.5.71 ... Error
  - Copy node_exporter -> 172.16.5.70 ... Error
  - Copy node_exporter -> 172.16.5.71 ... Error
  - Copy node_exporter -> 172.16.5.72 ... Error
  - Copy node_exporter -> 172.16.5.69 ... Error
  - Copy blackbox_exporter -> 172.16.5.70 ... Error
  - Copy blackbox_exporter -> 172.16.5.71 ... Error
  - Copy blackbox_exporter -> 172.16.5.72 ... Error
  - Copy blackbox_exporter -> 172.16.5.69 ... Error

Error: Process exited with status 1

**Comment by fzhedu** [comment]
[tiup-cluster-debug-2020-04-08-23-02-16.log](https://github.com/pingcap-incubator/tiup-cluster/files/4453740/tiup-cluster-debug-2020-04-08-23-02-16.log)

**Comment by lonng** [comment]
`ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain`

Seems that you the authentication you provided is invalid, please make sure the password correct or the identity_file path correct.

**Comment by fzhedu** [comment]
[tiup-cluster-debug-2020-04-09-10-44-12.log](https://github.com/pingcap-incubator/tiup-cluster/files/4453759/tiup-cluster-debug-2020-04-09-10-44-12.log)

tiup cluster deploy tidb-test v4.0.0-beta.2 ./topology.yaml --user root -i ~/.ssh/id_rsa

**Comment by lonng** [comment]
Please make sure that you have permission on the deploy directory and the data directory.
That directory should have `x` permission because we will copy files into them. ref: https://superuser.com/questions/168578/why-must-a-folder-be-executable
